### ISSUE TITLE
Permission requested to start a new repo based on your code.

### ISSUE THREAD

**Issue by circuitfry** [deanm1278/arduinoRibbonController#1]
Hey, Dean. You're more active on github and I wanted to write a message to you as quick as I can. I guess github doesn't have a private message system, but your reddit account hasn't had activity in 11 months, so, I'll just send this to you here ahahaha

I think you might (maaaybe?) remember me from asking questions about your softpot guitar project. I put it down for a little while, but I picked it up again recently, and while it's not fully finished, it's coded to the point where I'd love to have the help of more experienced people on the project. Mostly with figuring out how the frets are separated and then I move on to how MIDI conversion works and how transmission is supposed to work (and then I *should* have a working instrument!)

I'm coming to you because I mostly edited your code and did tons of documentation throughout the code in the form of comments for self-study purposes. It is suited for a guitar using a different microcontroller (the Pro Micro ATmega32u4) and using less parts (a single button for strumming and three softpot strings). The idea is to make a "generalized" guitar that anyone can put together for a low budget.

The big reason I'm coming to you is that you hold copyright over your code, and not only do I want to publish my version, I want to license my version under the GPL v3. I'm not a copyright expert but I imagine it'd be a matter of casual permission and blessing. It's entirely up to you, as you wrote the bulk of the code I'm basing this "general guitar project" off of. If you would rather I pick a different license or specify what would be best for me to do, I would really appreciate that. Whatever is fine with you is what's important.

**Comment by deanm1278** [comment]
Hey! yea go for it. All I would ask is you give credit and link to the original in your code. Have fun!

**Comment by circuitfry** [comment]
This is fantastic news, Dean, thanks so much! I've gotten started on the subreddit if you want to have a look!

https://www.reddit.com/r/arduino/comments/55i4ok/arduino_midi_controller_project/
