### ISSUE TITLE
Arduino Code errors

### ISSUE THREAD

**Issue by fiachra7** [deanm1278/arduinoRibbonController#2]
Great Work Dean, I'm trying to re-create your magnificent project over the xmas holidays however I'm getting some errors when verifying your Arduino code
![croppercapture 11](https://cloud.githubusercontent.com/assets/24970102/21739323/31646a3a-d490-11e6-9461-652115432c54.jpg)

**Comment by brandonwkipp** [comment]
Hi @fiachra7 

The reason you're getting that error is because you didn't download the extra libraries. You need them, otherwise the code can't access the functions it needs.

**Comment by fiachra7** [comment]
Thanks Brandon
